name: check compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y gcc libncurses5-dev
      - name: compilation
        run: |
          make
          if [ $? -ne 0 ]; then
            exit 1
          fi